services:
  - type: web
    name: veltor-airdrop-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN